cluster_config:
  name: kubernetes

sysdig_endpoint:
  region: us4
  access_key_existing_secret: sysdig-agent-secret
# cluster_type: gke-autopilot # Uncomment if using GKE Autopilot

features:
  kubernetes_metadata:
    enabled: true

  posture:
    host_posture:
      enabled: true
    cluster_posture:
      enabled: true

  vulnerability_management:
    host_vulnerability_management:
      enabled: true
    container_vulnerability_management:
      enabled: true
    in_use:
      enabled: true

  detections:
    kubernetes_audit:
      enabled: true
    malware_control:
      enabled: true

  respond:
    response_actions:
      enabled: true

host:
  driver: universal_ebpf